# Generated by Django 4.0.5 on 2022-10-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categoryproject',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='companyname',
            field=models.CharField(max_length=150),
        ),
    ]
