# Generated by Django 4.0.5 on 2022-10-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('mobile', models.CharField(max_length=15)),
                ('Message', models.CharField(max_length=1000)),
            ],
        ),
    ]
