# Generated by Django 4.0.5 on 2022-10-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Name',
            new_name='name',
        ),
    ]
