# Generated by Django 4.0.5 on 2022-10-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_message_contactus_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=11)),
                ('Alternate_Phone_no', models.CharField(max_length=11)),
                ('Instagram', models.URLField(max_length=250)),
                ('Facebook', models.URLField(max_length=250)),
                ('Twitter', models.URLField(max_length=250)),
                ('Youtube', models.URLField(max_length=250)),
                ('EmailId', models.EmailField(max_length=100)),
            ],
        ),
    ]
