# Generated by Django 4.0.5 on 2022-10-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_details',
            name='Location',
            field=models.CharField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d30711292.110871688!2d64.43748693609942!3d20.01115759964804!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30635ff06b92b791%3A0xd78c4fa1854213a6!2sIndia!5e0!3m2!1sen!2sin!4v1666597009340!5m2!1sen!2sin', max_length=1000),
        ),
    ]
