# Generated by Django 4.0.5 on 2022-10-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_image', models.ImageField(upload_to='')),
                ('Service_provided', models.CharField(max_length=20)),
                ('Service_description', models.CharField(max_length=50)),
            ],
        ),
    ]
