# Generated by Django 4.0.5 on 2022-10-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Service_description',
            field=models.CharField(max_length=100),
        ),
    ]
