# Generated by Django 4.0.5 on 2022-10-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_services_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Service_image',
            field=models.ImageField(upload_to='services/'),
        ),
    ]
