# Generated by Django 4.0.5 on 2022-10-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_services_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Service_image',
            field=models.CharField(max_length=25),
        ),
    ]
