# Generated by Django 4.0.5 on 2022-10-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='navigantionlinks',
            field=models.CharField(default='#', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='navigations',
            field=models.CharField(default='Home', max_length=12),
        ),
    ]
