# Generated by Django 4.0.5 on 2022-10-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homepage_navigantionlinks_homepage_navigations'),
    ]

    operations = [
        migrations.CreateModel(
            name='navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigations', models.CharField(default='Home', max_length=12)),
                ('navigantionlinks', models.CharField(default='#', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='navigantionlinks',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='navigations',
        ),
    ]
