# Generated by Django 4.0.5 on 2022-10-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='message',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='profession',
            field=models.CharField(max_length=40),
        ),
    ]
