# Generated by Django 4.0.5 on 2022-10-24 09:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_testimonials_image_alter_testimonials_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
